#ifndef __serial_RPC_CLIENT_H
#define __serial_RPC_CLIENT_H 1
/*
 * Copyright (c) 2010, ETH Zurich.
 * All rights reserved.
 * 
 * INTERFACE NAME: serial
 * INTEFACE FILE: /home/andreas/barrelfish/new_test2/if/serial.if
 * INTERFACE DESCRIPTION: Serial characters
 * 
 * This file is distributed under the terms in the attached LICENSE
 * file. If you do not find this file, copies can be found by
 * writing to:
 * ETH Zurich D-INFK, Universitaetstr.6, CH-8092 Zurich.
 * Attn: Systems Group.
 * 
 * THIS FILE IS AUTOMATICALLY GENERATED BY FLOUNDER: DO NOT EDIT!
 */

/*
 * RPC client
 */

#include <if/serial_defs.h>

/*
 * Forward declaration of binding type
 */
struct serial_rpc_client;

/*
 * Function signatures
 */

/*
 * VTable struct definition for the interface
 */
struct serial_rpc_vtbl {
};

/*
 * The Binding structure
 */
struct serial_rpc_client {
    struct serial_binding *b;
    struct serial_rpc_vtbl vtbl;
    bool rpc_in_progress;
    bool reply_present;
    errval_t async_error;
    struct waitset rpc_waitset;
    struct waitset_chanstate dummy_chanstate;
};

/*
 * Function to initialise an RPC client
 */
extern  errval_t serial_rpc_client_init(struct serial_rpc_client *rpc, struct serial_binding *binding);

#endif // __serial_RPC_CLIENT_H
