/*
 * Copyright (c) 2010, ETH Zurich.
 * All rights reserved.
 * 
 * INTERFACE NAME: empty
 * INTEFACE FILE: /home/andreas/barrelfish/new_test2/if/empty.if
 * INTERFACE DESCRIPTION: Empty interface
 * 
 * This file is distributed under the terms in the attached LICENSE
 * file. If you do not find this file, copies can be found by
 * writing to:
 * ETH Zurich D-INFK, Universitaetstr.6, CH-8092 Zurich.
 * Attn: Systems Group.
 * 
 * THIS FILE IS AUTOMATICALLY GENERATED BY FLOUNDER: DO NOT EDIT!
 */

#include <barrelfish/barrelfish.h>
#include <flounder/flounder_support.h>
#include <if/empty_defs.h>

/*
 * Export function
 */
 errval_t empty_export(void *st, idc_export_callback_fn *export_cb, empty_connect_fn *connect_cb, struct waitset *ws, idc_export_flags_t flags)
{
    struct empty_export *e = malloc(sizeof(struct empty_export ));
    if (e == NULL) {
        return(LIB_ERR_MALLOC_FAIL);
    }
    
    // fill in common parts of export struct
    e->connect_cb = connect_cb;
    e->waitset = ws;
    e->st = st;
    (e->common).export_callback = export_cb;
    (e->common).flags = flags;
    (e->common).connect_cb_st = e;
    (e->common).export_cb_st = st;
    
    // fill in connect handler for each enabled backend
    #ifdef CONFIG_FLOUNDER_BACKEND_LMP
    (e->common).lmp_connect_callback = empty_lmp_connect_handler;
    #endif // CONFIG_FLOUNDER_BACKEND_LMP
    #ifdef CONFIG_FLOUNDER_BACKEND_UMP
    (e->common).ump_connect_callback = empty_ump_connect_handler;
    #endif // CONFIG_FLOUNDER_BACKEND_UMP
    #ifdef CONFIG_FLOUNDER_BACKEND_UMP_IPI
    (e->common).ump_connect_callback = empty_ump_ipi_connect_handler;
    #endif // CONFIG_FLOUNDER_BACKEND_UMP_IPI
    #ifdef CONFIG_FLOUNDER_BACKEND_MULTIHOP
    (e->common).multihop_connect_callback = empty_multihop_connect_handler;
    #endif // CONFIG_FLOUNDER_BACKEND_MULTIHOP
    #ifdef CONFIG_FLOUNDER_BACKEND_UDN
    (e->common).udn_connect_callback = empty_udn_connect_handler;
    #endif // CONFIG_FLOUNDER_BACKEND_UDN
    
    return(idc_export_service(&(e->common)));
}


/*
 * Generic bind function
 */
static  void empty_bind_continuation_direct(void *st, errval_t err, struct empty_binding *_binding)
{
    // This bind cont function uses the different backends in the following order:
    // lmp ump_ipi ump multihop udn
    
    struct flounder_generic_bind_attempt *b = st;
    switch (b->driver_num) {
    case 0:
        (b->driver_num)++;
        #ifdef CONFIG_FLOUNDER_BACKEND_LMP
        // try next backend
        b->binding = malloc(sizeof(struct empty_lmp_binding ));
        assert((b->binding) != NULL);
        err = empty_lmp_bind(b->binding, b->iref, empty_bind_continuation_direct, b, b->waitset, b->flags, DEFAULT_LMP_BUF_WORDS);
        if (err_is_fail(err)) {
            free(b->binding);
            _binding = NULL;
            goto out;
        } else {
            return;
        }
        #else
        // skip non-enabled backend (fall through)
        #endif // CONFIG_FLOUNDER_BACKEND_LMP
    case 1:
        #ifdef CONFIG_FLOUNDER_BACKEND_LMP
        if (err_is_ok(err)) {
            goto out;
        } else {
            free(b->binding);
            if (err_no(err) == MON_ERR_IDC_BIND_NOT_SAME_CORE) {
                goto try_next_1;
            } else {
                // report permanent failure to user
                _binding = NULL;
                goto out;
            }
        }
        try_next_1:
        #endif // CONFIG_FLOUNDER_BACKEND_LMP
        (b->driver_num)++;
        #ifdef CONFIG_FLOUNDER_BACKEND_UMP_IPI
        // try next backend
        b->binding = malloc(sizeof(struct empty_ump_ipi_binding ));
        assert((b->binding) != NULL);
        err = empty_ump_ipi_bind(b->binding, b->iref, empty_bind_continuation_direct, b, b->waitset, b->flags, DEFAULT_UMP_BUFLEN, DEFAULT_UMP_BUFLEN);
        if (err_is_fail(err)) {
            free(b->binding);
            _binding = NULL;
            goto out;
        } else {
            return;
        }
        #else
        // skip non-enabled backend (fall through)
        #endif // CONFIG_FLOUNDER_BACKEND_UMP_IPI
    case 2:
        #ifdef CONFIG_FLOUNDER_BACKEND_UMP_IPI
        if (err_is_ok(err)) {
            goto out;
        } else {
            free(b->binding);
            if (true) {
                goto try_next_2;
            } else {
                // report permanent failure to user
                _binding = NULL;
                goto out;
            }
        }
        try_next_2:
        #endif // CONFIG_FLOUNDER_BACKEND_UMP_IPI
        (b->driver_num)++;
        #ifdef CONFIG_FLOUNDER_BACKEND_UMP
        // try next backend
        b->binding = malloc(sizeof(struct empty_ump_binding ));
        assert((b->binding) != NULL);
        err = empty_ump_bind(b->binding, b->iref, empty_bind_continuation_direct, b, b->waitset, b->flags, DEFAULT_UMP_BUFLEN, DEFAULT_UMP_BUFLEN);
        if (err_is_fail(err)) {
            free(b->binding);
            _binding = NULL;
            goto out;
        } else {
            return;
        }
        #else
        // skip non-enabled backend (fall through)
        #endif // CONFIG_FLOUNDER_BACKEND_UMP
    case 3:
        #ifdef CONFIG_FLOUNDER_BACKEND_UMP
        if (err_is_ok(err)) {
            goto out;
        } else {
            free(b->binding);
            if (true) {
                goto try_next_3;
            } else {
                // report permanent failure to user
                _binding = NULL;
                goto out;
            }
        }
        try_next_3:
        #endif // CONFIG_FLOUNDER_BACKEND_UMP
        (b->driver_num)++;
        #ifdef CONFIG_FLOUNDER_BACKEND_MULTIHOP
        // try next backend
        b->binding = malloc(sizeof(struct empty_multihop_binding ));
        assert((b->binding) != NULL);
        err = empty_multihop_bind(b->binding, b->iref, empty_bind_continuation_direct, b, b->waitset, b->flags);
        if (err_is_fail(err)) {
            free(b->binding);
            _binding = NULL;
            goto out;
        } else {
            return;
        }
        #else
        // skip non-enabled backend (fall through)
        #endif // CONFIG_FLOUNDER_BACKEND_MULTIHOP
    case 4:
        #ifdef CONFIG_FLOUNDER_BACKEND_MULTIHOP
        if (err_is_ok(err)) {
            goto out;
        } else {
            free(b->binding);
            if (true) {
                goto try_next_4;
            } else {
                // report permanent failure to user
                _binding = NULL;
                goto out;
            }
        }
        try_next_4:
        #endif // CONFIG_FLOUNDER_BACKEND_MULTIHOP
        (b->driver_num)++;
        #ifdef CONFIG_FLOUNDER_BACKEND_UDN
        // try next backend
        b->binding = malloc(sizeof(struct empty_udn_binding ));
        assert((b->binding) != NULL);
        err = empty_udn_bind(b->binding, b->iref, empty_bind_continuation_direct, b, b->waitset, b->flags);
        if (err_is_fail(err)) {
            free(b->binding);
            _binding = NULL;
            goto out;
        } else {
            return;
        }
        #else
        // skip non-enabled backend (fall through)
        #endif // CONFIG_FLOUNDER_BACKEND_UDN
    case 5:
        #ifdef CONFIG_FLOUNDER_BACKEND_UDN
        if (err_is_ok(err)) {
            goto out;
        } else {
            free(b->binding);
            if (!true) {
                _binding = NULL;
                goto out;
            }
        }
        #endif // CONFIG_FLOUNDER_BACKEND_UDN
        err = FLOUNDER_ERR_GENERIC_BIND_NO_MORE_DRIVERS;
        _binding = NULL;
        goto out;
    default:
        assert(!("invalid state"));
    }
    
    out:
    ((empty_bind_continuation_fn *)(b->callback))(b->st, err, _binding);
    free(b);
}

static  void empty_bind_contination_multihop(void *st, errval_t err, struct empty_binding *_binding)
{
    // This bind cont function uses the different backends in the following order:
    // lmp multihop ump_ipi ump udn
    
    struct flounder_generic_bind_attempt *b = st;
    switch (b->driver_num) {
    case 0:
        (b->driver_num)++;
        #ifdef CONFIG_FLOUNDER_BACKEND_LMP
        // try next backend
        b->binding = malloc(sizeof(struct empty_lmp_binding ));
        assert((b->binding) != NULL);
        err = empty_lmp_bind(b->binding, b->iref, empty_bind_contination_multihop, b, b->waitset, b->flags, DEFAULT_LMP_BUF_WORDS);
        if (err_is_fail(err)) {
            free(b->binding);
            _binding = NULL;
            goto out;
        } else {
            return;
        }
        #else
        // skip non-enabled backend (fall through)
        #endif // CONFIG_FLOUNDER_BACKEND_LMP
    case 1:
        #ifdef CONFIG_FLOUNDER_BACKEND_LMP
        if (err_is_ok(err)) {
            goto out;
        } else {
            free(b->binding);
            if (err_no(err) == MON_ERR_IDC_BIND_NOT_SAME_CORE) {
                goto try_next_1;
            } else {
                // report permanent failure to user
                _binding = NULL;
                goto out;
            }
        }
        try_next_1:
        #endif // CONFIG_FLOUNDER_BACKEND_LMP
        (b->driver_num)++;
        #ifdef CONFIG_FLOUNDER_BACKEND_MULTIHOP
        // try next backend
        b->binding = malloc(sizeof(struct empty_multihop_binding ));
        assert((b->binding) != NULL);
        err = empty_multihop_bind(b->binding, b->iref, empty_bind_contination_multihop, b, b->waitset, b->flags);
        if (err_is_fail(err)) {
            free(b->binding);
            _binding = NULL;
            goto out;
        } else {
            return;
        }
        #else
        // skip non-enabled backend (fall through)
        #endif // CONFIG_FLOUNDER_BACKEND_MULTIHOP
    case 2:
        #ifdef CONFIG_FLOUNDER_BACKEND_MULTIHOP
        if (err_is_ok(err)) {
            goto out;
        } else {
            free(b->binding);
            if (true) {
                goto try_next_2;
            } else {
                // report permanent failure to user
                _binding = NULL;
                goto out;
            }
        }
        try_next_2:
        #endif // CONFIG_FLOUNDER_BACKEND_MULTIHOP
        (b->driver_num)++;
        #ifdef CONFIG_FLOUNDER_BACKEND_UMP_IPI
        // try next backend
        b->binding = malloc(sizeof(struct empty_ump_ipi_binding ));
        assert((b->binding) != NULL);
        err = empty_ump_ipi_bind(b->binding, b->iref, empty_bind_contination_multihop, b, b->waitset, b->flags, DEFAULT_UMP_BUFLEN, DEFAULT_UMP_BUFLEN);
        if (err_is_fail(err)) {
            free(b->binding);
            _binding = NULL;
            goto out;
        } else {
            return;
        }
        #else
        // skip non-enabled backend (fall through)
        #endif // CONFIG_FLOUNDER_BACKEND_UMP_IPI
    case 3:
        #ifdef CONFIG_FLOUNDER_BACKEND_UMP_IPI
        if (err_is_ok(err)) {
            goto out;
        } else {
            free(b->binding);
            if (true) {
                goto try_next_3;
            } else {
                // report permanent failure to user
                _binding = NULL;
                goto out;
            }
        }
        try_next_3:
        #endif // CONFIG_FLOUNDER_BACKEND_UMP_IPI
        (b->driver_num)++;
        #ifdef CONFIG_FLOUNDER_BACKEND_UMP
        // try next backend
        b->binding = malloc(sizeof(struct empty_ump_binding ));
        assert((b->binding) != NULL);
        err = empty_ump_bind(b->binding, b->iref, empty_bind_contination_multihop, b, b->waitset, b->flags, DEFAULT_UMP_BUFLEN, DEFAULT_UMP_BUFLEN);
        if (err_is_fail(err)) {
            free(b->binding);
            _binding = NULL;
            goto out;
        } else {
            return;
        }
        #else
        // skip non-enabled backend (fall through)
        #endif // CONFIG_FLOUNDER_BACKEND_UMP
    case 4:
        #ifdef CONFIG_FLOUNDER_BACKEND_UMP
        if (err_is_ok(err)) {
            goto out;
        } else {
            free(b->binding);
            if (true) {
                goto try_next_4;
            } else {
                // report permanent failure to user
                _binding = NULL;
                goto out;
            }
        }
        try_next_4:
        #endif // CONFIG_FLOUNDER_BACKEND_UMP
        (b->driver_num)++;
        #ifdef CONFIG_FLOUNDER_BACKEND_UDN
        // try next backend
        b->binding = malloc(sizeof(struct empty_udn_binding ));
        assert((b->binding) != NULL);
        err = empty_udn_bind(b->binding, b->iref, empty_bind_contination_multihop, b, b->waitset, b->flags);
        if (err_is_fail(err)) {
            free(b->binding);
            _binding = NULL;
            goto out;
        } else {
            return;
        }
        #else
        // skip non-enabled backend (fall through)
        #endif // CONFIG_FLOUNDER_BACKEND_UDN
    case 5:
        #ifdef CONFIG_FLOUNDER_BACKEND_UDN
        if (err_is_ok(err)) {
            goto out;
        } else {
            free(b->binding);
            if (!true) {
                _binding = NULL;
                goto out;
            }
        }
        #endif // CONFIG_FLOUNDER_BACKEND_UDN
        err = FLOUNDER_ERR_GENERIC_BIND_NO_MORE_DRIVERS;
        _binding = NULL;
        goto out;
    default:
        assert(!("invalid state"));
    }
    
    out:
    ((empty_bind_continuation_fn *)(b->callback))(b->st, err, _binding);
    free(b);
}

 errval_t empty_bind(iref_t iref, empty_bind_continuation_fn *_continuation, void *st, struct waitset *waitset, idc_bind_flags_t flags)
{
    // allocate state
    struct flounder_generic_bind_attempt *b = malloc(sizeof(struct flounder_generic_bind_attempt ));
    if (b == NULL) {
        return(LIB_ERR_MALLOC_FAIL);
    }
    
    // fill in binding state
    b->iref = iref;
    b->waitset = waitset;
    b->driver_num = 0;
    b->callback = _continuation;
    b->st = st;
    b->flags = flags;
    
    if (flags & IDC_BIND_FLAG_MULTIHOP) {
        empty_bind_contination_multihop(b, SYS_ERR_OK, NULL);
    } else {
        empty_bind_continuation_direct(b, SYS_ERR_OK, NULL);
    }
    
    return(SYS_ERR_OK);
}

/*
 * Copyright (c) 2010, ETH Zurich.
 * All rights reserved.
 * 
 * INTERFACE NAME: empty
 * INTEFACE FILE: /home/andreas/barrelfish/new_test2/if/empty.if
 * INTERFACE DESCRIPTION: Empty interface
 * 
 * This file is distributed under the terms in the attached LICENSE
 * file. If you do not find this file, copies can be found by
 * writing to:
 * ETH Zurich D-INFK, Universitaetstr.6, CH-8092 Zurich.
 * Attn: Systems Group.
 * 
 * THIS FILE IS AUTOMATICALLY GENERATED BY FLOUNDER: DO NOT EDIT!
 */

/*
 * Generated Stub for LMP on tilepro
 */

#include <string.h>
#include <barrelfish/barrelfish.h>
#include <flounder/flounder_support.h>
#include <flounder/flounder_support_lmp.h>
#include <if/empty_defs.h>

/*
 * Send handler functions
 */
static  void empty_unused__lmp_send_handler(void *arg)
{
    // Get the binding state from our argument pointer
    struct empty_binding *_binding = arg;
    struct empty_lmp_binding *b = arg;
    errval_t err;
    
    // Switch on current outgoing message fragment
    switch (_binding->tx_msg_fragment) {
    case 0:
        err = lmp_chan_send1(&(b->chan), b->flags, NULL_CAP, empty_unused__msgnum);
        if (err_is_ok(err)) {
            _binding->tx_msgnum = 0;
            flounder_support_trigger_chan(&(_binding->tx_cont_chanstate));
            flounder_support_trigger_chan(&(_binding->register_chanstate));
            return;
        } else {
            break;
        }
    default:
        assert(!("invalid fragment"));
        err = FLOUNDER_ERR_INVALID_STATE;
    }
    
    if (lmp_err_is_transient(err)) {
        // Construct retry closure and register it
        struct event_closure retry_closure = (struct event_closure){  .handler = empty_unused__lmp_send_handler,  .arg = arg };
        err = lmp_chan_register_send(&(b->chan), _binding->waitset, retry_closure);
        assert(err_is_ok(err));
    } else {
        // Report error to user
        (_binding->error_handler)(_binding, err);
        _binding->tx_msgnum = 0;
        flounder_support_trigger_chan(&(_binding->register_chanstate));
        flounder_support_deregister_chan(&(_binding->tx_cont_chanstate));
    }
}


/*
 * Message sender functions
 */
static  errval_t empty_unused__lmp_send(struct empty_binding *_binding, struct event_closure _continuation)
{
    // check that we can accept an outgoing message
    if ((_binding->tx_msgnum) != 0) {
        return(FLOUNDER_ERR_TX_BUSY);
    }
    
    // register send continuation
    if ((_continuation.handler) != NULL) {
        errval_t _err;
        _err = flounder_support_register(_binding->waitset, &(_binding->tx_cont_chanstate), _continuation, false);
        // may fail if previous continuation hasn't fired yet
        if (err_is_fail(_err)) {
            if (err_no(_err) == LIB_ERR_CHAN_ALREADY_REGISTERED) {
                return(FLOUNDER_ERR_TX_BUSY);
            } else {
                assert(!("shouldn't happen"));
                return(_err);
            }
        }
    }
    
    // store message number and arguments
    _binding->tx_msgnum = empty_unused__msgnum;
    _binding->tx_msg_fragment = 0;
    FL_DEBUG("lmp TX empty.unused\n");
    
    // try to send!
    empty_unused__lmp_send_handler(_binding);
    
    return(SYS_ERR_OK);
}


/*
 * Send vtable
 */
static  struct empty_tx_vtbl empty_lmp_tx_vtbl = {
    .unused = empty_unused__lmp_send,
};
/*
 * Receive handler
 */
 void empty_lmp_rx_handler(void *arg)
{
    // Get the binding state from our argument pointer
    struct empty_binding *_binding = arg;
    struct empty_lmp_binding *b = arg;
    errval_t err;
    
    struct lmp_recv_msg msg = LMP_RECV_MSG_INIT;
    struct capref cap;
    struct event_closure recv_closure = (struct event_closure){  .handler = empty_lmp_rx_handler,  .arg = arg };
    
    do {
        // try to retrieve a message from the channel
        err = lmp_chan_recv(&(b->chan), &msg, &cap);
        // check if we succeeded
        if (err_is_fail(err)) {
            if (err_no(err) == LIB_ERR_NO_LMP_MSG) {
                // no message
                break;
            } else {
                // real error
                (_binding->error_handler)(_binding, err_push(err, LIB_ERR_LMP_CHAN_RECV));
                return;
            }
        }
        
        // allocate a new receive slot if needed
        if (!capref_is_null(cap)) {
            err = lmp_chan_alloc_recv_slot(&(b->chan));
            if (err_is_fail(err)) {
                (_binding->error_handler)(_binding, err_push(err, LIB_ERR_LMP_ALLOC_RECV_SLOT));
            }
        }
        
        // is this the start of a new message?
        if ((_binding->rx_msgnum) == 0) {
            // check message length
            if (((msg.buf).msglen) == 0) {
                (_binding->error_handler)(_binding, FLOUNDER_ERR_RX_EMPTY_MSG);
                break;
            }
            // unmarshall message number from first word, set fragment to 0
            _binding->rx_msgnum = (((msg.words)[0]) & 0xffff);
            _binding->rx_msg_fragment = 0;
        }
        
        // switch on message number and fragment number
        switch (_binding->rx_msgnum) {
        case empty_unused__msgnum:
            switch (_binding->rx_msg_fragment) {
            case 0:
                // check length
                if (((msg.buf).msglen) != 1) {
                    (_binding->error_handler)(_binding, FLOUNDER_ERR_RX_INVALID_LENGTH);
                    goto out;
                }
                
                
                FL_DEBUG("lmp RX empty.unused\n");
                assert(((_binding->rx_vtbl).unused) != NULL);
                ((_binding->rx_vtbl).unused)(_binding);
                _binding->rx_msgnum = 0;
                break;
            default:
                (_binding->error_handler)(_binding, FLOUNDER_ERR_INVALID_STATE);
                goto out;
            }
            break;
        default:
            (_binding->error_handler)(_binding, FLOUNDER_ERR_RX_INVALID_MSGNUM);
            goto out;
        }
    } while (err_is_ok(err));
    out:
    // re-register for another receive notification
    err = lmp_chan_register_recv(&(b->chan), _binding->waitset, recv_closure);
    assert(err_is_ok(err));
}


/*
 * Control functions
 */
static  bool empty_lmp_can_send(struct empty_binding *b)
{
    return((b->tx_msgnum) == 0);
}

static  errval_t empty_lmp_register_send(struct empty_binding *b, struct waitset *ws, struct event_closure _continuation)
{
    return(flounder_support_register(ws, &(b->register_chanstate), _continuation, empty_lmp_can_send(b)));
}

static  void empty_lmp_default_error_handler(struct empty_binding *b, errval_t err)
{
    DEBUG_ERR(err, "asynchronous error in Flounder-generated empty lmp binding (default handler)");
    abort();
}

static  errval_t empty_lmp_change_waitset(struct empty_binding *_binding, struct waitset *ws)
{
    struct empty_lmp_binding *b = (void *)(_binding);
    
    // Migrate register and TX continuation notifications
    flounder_support_migrate_notify(&(_binding->register_chanstate), ws);
    flounder_support_migrate_notify(&(_binding->tx_cont_chanstate), ws);
    
    // change waitset on binding
    _binding->waitset = ws;
    
    // Migrate send and receive notifications
    lmp_chan_migrate_recv(&(b->chan), ws);
    lmp_chan_migrate_send(&(b->chan), ws);
    
    return(SYS_ERR_OK);
}

static  errval_t empty_lmp_control(struct empty_binding *_binding, idc_control_t control)
{
    struct empty_lmp_binding *b = (void *)(_binding);
    
    b->flags = idc_control_to_lmp_flags(control, b->flags);
    
    return(SYS_ERR_OK);
}

/*
 * Functions to initialise/destroy the binding state
 */
 void empty_lmp_init(struct empty_lmp_binding *b, struct waitset *waitset)
{
    (b->b).st = NULL;
    (b->b).waitset = waitset;
    event_mutex_init(&((b->b).mutex), waitset);
    (b->b).can_send = empty_lmp_can_send;
    (b->b).register_send = empty_lmp_register_send;
    (b->b).error_handler = empty_lmp_default_error_handler;
    (b->b).tx_vtbl = empty_lmp_tx_vtbl;
    memset(&((b->b).rx_vtbl), 0, sizeof((b->b).rx_vtbl));
    flounder_support_waitset_chanstate_init(&((b->b).register_chanstate));
    flounder_support_waitset_chanstate_init(&((b->b).tx_cont_chanstate));
    (b->b).tx_msgnum = 0;
    (b->b).rx_msgnum = 0;
    (b->b).tx_msg_fragment = 0;
    (b->b).rx_msg_fragment = 0;
    (b->b).tx_str_pos = 0;
    (b->b).rx_str_pos = 0;
    (b->b).tx_str_len = 0;
    (b->b).rx_str_len = 0;
    (b->b).bind_cont = NULL;
    lmp_chan_init(&(b->chan));
    (b->b).change_waitset = empty_lmp_change_waitset;
    (b->b).control = empty_lmp_control;
    b->flags = LMP_SEND_FLAGS_DEFAULT;
}

 void empty_lmp_destroy(struct empty_lmp_binding *b)
{
    flounder_support_waitset_chanstate_destroy(&((b->b).register_chanstate));
    flounder_support_waitset_chanstate_destroy(&((b->b).tx_cont_chanstate));
    lmp_chan_destroy(&(b->chan));
}


/*
 * Bind function
 */
static  void empty_lmp_bind_continuation(void *st, errval_t err, struct lmp_chan *chan)
{
    struct empty_lmp_binding *b = st;
    
    if (err_is_ok(err)) {
        // allocate a cap receive slot
        err = lmp_chan_alloc_recv_slot(chan);
        if (err_is_fail(err)) {
            err = err_push(err, LIB_ERR_LMP_ALLOC_RECV_SLOT);
            goto fail;
        }
        
        // register for receive
        err = lmp_chan_register_recv(chan, (b->b).waitset, (struct event_closure){  .handler = empty_lmp_rx_handler,  .arg = b });
        if (err_is_fail(err)) {
            err = err_push(err, LIB_ERR_CHAN_REGISTER_RECV);
            goto fail;
        }
    } else {
        fail:
        empty_lmp_destroy(b);
    }
    
    ((b->b).bind_cont)((b->b).st, err, &(b->b));
}

 errval_t empty_lmp_bind(struct empty_lmp_binding *b, iref_t iref, empty_bind_continuation_fn *_continuation, void *st, struct waitset *waitset, idc_bind_flags_t flags, size_t lmp_buflen)
{
    errval_t err;
    empty_lmp_init(b, waitset);
    (b->b).st = st;
    (b->b).bind_cont = _continuation;
    err = lmp_chan_bind(&(b->chan), (struct lmp_bind_continuation){  .handler = empty_lmp_bind_continuation,  .st = b }, &((b->b).event_qnode), iref, lmp_buflen);
    if (err_is_fail(err)) {
        empty_lmp_destroy(b);
    }
    return(err);
}


/*
 * Connect callback for export
 */
 errval_t empty_lmp_connect_handler(void *st, size_t buflen_words, struct capref endpoint, struct lmp_chan **retchan)
{
    struct empty_export *e = st;
    errval_t err;
    
    // allocate storage for binding
    struct empty_lmp_binding *b = malloc(sizeof(struct empty_lmp_binding ));
    if (b == NULL) {
        return(LIB_ERR_MALLOC_FAIL);
    }
    
    struct empty_binding *_binding = &(b->b);
    empty_lmp_init(b, e->waitset);
    
    // run user's connect handler
    err = ((e->connect_cb)(e->st, _binding));
    if (err_is_fail(err)) {
        // connection refused
        empty_lmp_destroy(b);
        return(err);
    }
    
    // accept the connection and setup the channel
    // FIXME: user policy needed to decide on the size of the message buffer?
    err = lmp_chan_accept(&(b->chan), buflen_words, endpoint);
    if (err_is_fail(err)) {
        err = err_push(err, LIB_ERR_LMP_CHAN_ACCEPT);
        (_binding->error_handler)(_binding, err);
        return(err);
    }
    
    // allocate a cap receive slot
    err = lmp_chan_alloc_recv_slot(&(b->chan));
    if (err_is_fail(err)) {
        err = err_push(err, LIB_ERR_LMP_ALLOC_RECV_SLOT);
        (_binding->error_handler)(_binding, err);
        return(err);
    }
    
    // register for receive
    err = lmp_chan_register_recv(&(b->chan), _binding->waitset, (struct event_closure){  .handler = empty_lmp_rx_handler,  .arg = b });
    if (err_is_fail(err)) {
        err = err_push(err, LIB_ERR_CHAN_REGISTER_RECV);
        (_binding->error_handler)(_binding, err);
        return(err);
    }
    
    *retchan = (&(b->chan));
    
    return(SYS_ERR_OK);
}

/*
 * Copyright (c) 2010, ETH Zurich.
 * All rights reserved.
 * 
 * INTERFACE NAME: empty
 * INTEFACE FILE: /home/andreas/barrelfish/new_test2/if/empty.if
 * INTERFACE DESCRIPTION: Empty interface
 * 
 * This file is distributed under the terms in the attached LICENSE
 * file. If you do not find this file, copies can be found by
 * writing to:
 * ETH Zurich D-INFK, Universitaetstr.6, CH-8092 Zurich.
 * Attn: Systems Group.
 * 
 * THIS FILE IS AUTOMATICALLY GENERATED BY FLOUNDER: DO NOT EDIT!
 */

#ifdef CONFIG_FLOUNDER_BACKEND_UDN

/*
 * Generated Stub for UDN
 */

#include <barrelfish/barrelfish.h>
#include <barrelfish/monitor_client.h>
#include <flounder/flounder_support.h>
#include <flounder/flounder_support_udn.h>
#include <if/empty_defs.h>

/*
 * Send handler function
 */
static  void empty_udn_send_handler(void *arg)
{
    // Get the binding state from our argument pointer
    struct empty_binding *_binding = arg;
    struct empty_udn_binding *b = arg;
    errval_t err;
    err = SYS_ERR_OK;
    
    struct udn_message msg;
    bool tx_notify = false;
    
    // do we need to (and can we) send a cap ack?
    if ((((b->udn_state).capst).tx_cap_ack) && flounder_stub_udn_can_send(&(b->udn_state))) {
        flounder_stub_udn_send_cap_ack(&(b->udn_state));
        ((b->udn_state).capst).tx_cap_ack = false;
        tx_notify = true;
    }
    
    // Switch on current outgoing message number
    switch (_binding->tx_msgnum) {
    case 0:
        break;
    case empty_unused__msgnum:
        // Switch on current outgoing message fragment
        switch (_binding->tx_msg_fragment) {
        case 0:
            // check if we can send another message
            if (!flounder_stub_udn_can_send(&(b->udn_state))) {
                tx_notify = true;
                break;
            }
            
            // send the next fragment
            msg.data_len = 0;
            msg.type = empty_unused__msgnum;
            udn_impl_send_msg(&(((b->udn_state).chan).send_chan), &msg);
            (_binding->tx_msg_fragment)++;
            _binding->tx_msgnum = 0;
            flounder_support_trigger_chan(&(_binding->tx_cont_chanstate));
            flounder_support_trigger_chan(&(_binding->register_chanstate));
            return;
        case 1:
            // we've sent all the fragments, we must just be waiting for caps
            assert((((b->udn_state).capst).tx_capnum) <= 0);
            break;
        default:
            assert(!("invalid fragment"));
            (_binding->error_handler)(_binding, FLOUNDER_ERR_INVALID_STATE);
        }
        break;
    default:
        assert(!("invalid msgnum"));
        (_binding->error_handler)(_binding, FLOUNDER_ERR_INVALID_STATE);
    }
    
    // Send a notification if necessary
    if (tx_notify) {
    }
}


/*
 * Capability sender function
 */
static  void empty_udn_cap_send_handler(void *arg)
{
    // Get the binding state from our argument pointer
    struct empty_binding *_binding = arg;
    struct empty_udn_binding *b = arg;
    errval_t err;
    err = SYS_ERR_OK;
    
    assert(((b->udn_state).capst).rx_cap_ack);
    assert(((b->udn_state).capst).monitor_mutex_held);
    
    // Switch on current outgoing message
    switch (_binding->tx_msgnum) {
    default:
        assert(!("invalid message number"));
        (_binding->error_handler)(_binding, FLOUNDER_ERR_INVALID_STATE);
    }
}


/*
 * Receive handler
 */
 void empty_udn_rx_handler(void *arg)
{
    // Get the binding state from our argument pointer
    struct empty_binding *_binding = arg;
    struct empty_udn_binding *b = arg;
    errval_t err;
    err = SYS_ERR_OK;
    
    struct udn_message *msg;
    int msgnum;
    
    while (true) {
        // try to retrieve a message from the channel
        err = udn_chan_recv(&((b->udn_state).chan), &msg);
        // check if we succeeded
        if (err_is_fail(err)) {
            if (err_no(err) == LIB_ERR_NO_UDN_MSG) {
                // no message
                break;
            } else {
                // real error
                (_binding->error_handler)(_binding, err_push(err, LIB_ERR_UDN_CHAN_RECV));
                return;
            }
        }
        
        // get msg num (type)
        msgnum = (msg->type);
        
        // is this a dummy message (ACK)?
        if (msgnum == FL_UDN_ACK) {
            goto loopnext;
        }
        
        // is this a cap ack for a pending tx message
        if (msgnum == FL_UDN_CAP_ACK) {
            assert(!(((b->udn_state).capst).rx_cap_ack));
            ((b->udn_state).capst).rx_cap_ack = true;
            if (((b->udn_state).capst).monitor_mutex_held) {
                empty_udn_cap_send_handler(b);
            }
            goto loopnext;
        }
        
        // is this the start of a new message?
        if ((_binding->rx_msgnum) == 0) {
            _binding->rx_msgnum = msgnum;
            _binding->rx_msg_fragment = 0;
        }
        
        // switch on message number and fragment number
        switch (_binding->rx_msgnum) {
        case empty_unused__msgnum:
            switch (_binding->rx_msg_fragment) {
            case 0:
                
                FL_DEBUG("udn RX empty.unused\n");
                assert(((_binding->rx_vtbl).unused) != NULL);
                ((_binding->rx_vtbl).unused)(_binding);
                _binding->rx_msgnum = 0;
                break;
            default:
                (_binding->error_handler)(_binding, FLOUNDER_ERR_INVALID_STATE);
                goto out;
            }
            break;
        default:
            (_binding->error_handler)(_binding, FLOUNDER_ERR_RX_INVALID_MSGNUM);
            goto out;
        }
        
        loopnext:
        // send an ack if the channel is now full
        if (flounder_stub_udn_needs_ack(&(b->udn_state))) {
            // run our send process if we need to
            if ((((b->udn_state).capst).tx_cap_ack) || ((_binding->tx_msgnum) != 0)) {
                empty_udn_send_handler(b);
            } else {
                flounder_stub_udn_send_ack(&(b->udn_state));
            }
        }
    }
    
    out:
    // register for receive notification
    err = udn_chan_register_recv(&((b->udn_state).chan), _binding->waitset, (struct event_closure){  .handler = empty_udn_rx_handler,  .arg = _binding });
    if (err_is_fail(err)) {
        (_binding->error_handler)(_binding, err_push(err, LIB_ERR_CHAN_REGISTER_RECV));
    }
    
    out_no_reregister:
    __attribute__((unused));
    // run our send process, if we need to
    if ((((b->udn_state).capst).tx_cap_ack) || ((_binding->tx_msgnum) != 0)) {
        empty_udn_send_handler(b);
    } else {
        // otherwise send a forced ack if the channel is now full
        if (flounder_stub_udn_needs_ack(&(b->udn_state))) {
            flounder_stub_udn_send_ack(&(b->udn_state));
        }
    }
}


/*
 * Cap send/receive handlers
 */
static  void empty_udn_cap_rx_handler(void *arg, errval_t success, struct capref cap, uint32_t capid)
{
    // Get the binding state from our argument pointer
    struct empty_binding *_binding = arg;
    struct empty_udn_binding *b = arg;
    errval_t err;
    err = SYS_ERR_OK;
    
    assert(capid == (((b->udn_state).capst).rx_capnum));
    
    // Check if there's an associated error
    // FIXME: how should we report this to the user? at present we just deliver a NULL capref
    if (err_is_fail(success)) {
        DEBUG_ERR(err, "error in cap transfer");
    }
    
    // Switch on current incoming message
    switch (_binding->rx_msgnum) {
    default:
        assert(!("invalid message number"));
        (_binding->error_handler)(_binding, FLOUNDER_ERR_INVALID_STATE);
    }
}


/*
 * Message sender functions
 */
static  errval_t empty_unused__udn_send(struct empty_binding *_binding, struct event_closure _continuation)
{
    // check that we can accept an outgoing message
    if ((_binding->tx_msgnum) != 0) {
        return(FLOUNDER_ERR_TX_BUSY);
    }
    
    // register send continuation
    if ((_continuation.handler) != NULL) {
        errval_t _err;
        _err = flounder_support_register(_binding->waitset, &(_binding->tx_cont_chanstate), _continuation, false);
        // may fail if previous continuation hasn't fired yet
        if (err_is_fail(_err)) {
            if (err_no(_err) == LIB_ERR_CHAN_ALREADY_REGISTERED) {
                return(FLOUNDER_ERR_TX_BUSY);
            } else {
                assert(!("shouldn't happen"));
                return(_err);
            }
        }
    }
    
    // store message number and arguments
    _binding->tx_msgnum = empty_unused__msgnum;
    _binding->tx_msg_fragment = 0;
    FL_DEBUG("udn TX empty.unused\n");
    
    // try to send!
    empty_udn_send_handler(_binding);
    
    return(SYS_ERR_OK);
}


/*
 * Send vtable
 */
static  struct empty_tx_vtbl empty_udn_tx_vtbl = {
    .unused = empty_unused__udn_send,
};
/*
 * Control functions
 */
static  bool empty_udn_can_send(struct empty_binding *b)
{
    return((b->tx_msgnum) == 0);
}

static  errval_t empty_udn_register_send(struct empty_binding *b, struct waitset *ws, struct event_closure _continuation)
{
    return(flounder_support_register(ws, &(b->register_chanstate), _continuation, empty_udn_can_send(b)));
}

static  void empty_udn_default_error_handler(struct empty_binding *b, errval_t err)
{
    DEBUG_ERR(err, "asynchronous error in Flounder-generated empty udn binding (default handler)");
    abort();
}

static  errval_t empty_udn_change_waitset(struct empty_binding *_binding, struct waitset *ws)
{
    struct empty_udn_binding *b = (void *)(_binding);
    errval_t err;
    
    // change waitset on private monitor binding if we have one
    if ((((b->udn_state).chan).monitor_binding) != get_monitor_binding()) {
        err = flounder_support_change_monitor_waitset(((b->udn_state).chan).monitor_binding, ws);
        if (err_is_fail(err)) {
            return(err_push(err, FLOUNDER_ERR_CHANGE_MONITOR_WAITSET));
        }
    }
    
    // change waitset on binding
    _binding->waitset = ws;
    
    // re-register for receive (if previously registered)
    err = udn_chan_deregister_recv(&((b->udn_state).chan));
    if (err_is_fail(err) && (err_no(err) != LIB_ERR_CHAN_NOT_REGISTERED)) {
        return(err_push(err, LIB_ERR_CHAN_DEREGISTER_RECV));
    }
    if (err_is_ok(err)) {
        err = udn_chan_register_recv(&((b->udn_state).chan), _binding->waitset, (struct event_closure){  .handler = empty_udn_rx_handler,  .arg = _binding });
        if (err_is_fail(err)) {
            return(err_push(err, LIB_ERR_CHAN_REGISTER_RECV));
        }
    }
    return(SYS_ERR_OK);
}

static  errval_t empty_udn_control(struct empty_binding *_binding, idc_control_t control)
{
    // no control flags are supported
    return(SYS_ERR_OK);
}


/*
 * Function to destroy the binding state
 */
 void empty_udn_destroy(struct empty_udn_binding *b)
{
    flounder_support_waitset_chanstate_destroy(&((b->b).register_chanstate));
    flounder_support_waitset_chanstate_destroy(&((b->b).tx_cont_chanstate));
    udn_chan_destroy(&((b->udn_state).chan));
}


/*
 * Bind function
 */
static  void empty_udn_bind_continuation(void *st, errval_t err, struct udn_chan *chan, struct capref notify_cap)
{
    struct empty_binding *_binding = st;
    struct empty_udn_binding *b = st;
    
    if (err_is_ok(err)) {
        // notify cap ignored
        // setup cap handlers
        (((b->udn_state).chan).cap_handlers).st = b;
        (((b->udn_state).chan).cap_handlers).cap_receive_handler = empty_udn_cap_rx_handler;
        // register for receive notification
        err = udn_chan_register_recv(&((b->udn_state).chan), _binding->waitset, (struct event_closure){  .handler = empty_udn_rx_handler,  .arg = _binding });
        if (err_is_fail(err)) {
            (_binding->error_handler)(_binding, err_push(err, LIB_ERR_CHAN_REGISTER_RECV));
        }
    } else {
        empty_udn_destroy(b);
    }
    
    (_binding->bind_cont)(_binding->st, err, _binding);
}

 errval_t empty_udn_init(struct empty_udn_binding *b, struct waitset *waitset, coreid_t dest_core_id, uint32_t out_chan_id, uint8_t dest_asid)
{
    errval_t err;
    struct empty_binding *_binding = &(b->b);
    (b->b).st = NULL;
    (b->b).waitset = waitset;
    event_mutex_init(&((b->b).mutex), waitset);
    (b->b).can_send = empty_udn_can_send;
    (b->b).register_send = empty_udn_register_send;
    (b->b).error_handler = empty_udn_default_error_handler;
    (b->b).tx_vtbl = empty_udn_tx_vtbl;
    memset(&((b->b).rx_vtbl), 0, sizeof((b->b).rx_vtbl));
    flounder_support_waitset_chanstate_init(&((b->b).register_chanstate));
    flounder_support_waitset_chanstate_init(&((b->b).tx_cont_chanstate));
    (b->b).tx_msgnum = 0;
    (b->b).rx_msgnum = 0;
    (b->b).tx_msg_fragment = 0;
    (b->b).rx_msg_fragment = 0;
    (b->b).tx_str_pos = 0;
    (b->b).rx_str_pos = 0;
    (b->b).tx_str_len = 0;
    (b->b).rx_str_len = 0;
    (b->b).bind_cont = NULL;
    flounder_stub_udn_state_init(&(b->udn_state), b);
    err = udn_chan_init(&((b->udn_state).chan), dest_core_id, out_chan_id, dest_asid);
    if (err_is_fail(err)) {
        empty_udn_destroy(b);
        return(err_push(err, LIB_ERR_UDN_CHAN_INIT));
    }
    
    (b->b).change_waitset = empty_udn_change_waitset;
    (b->b).control = empty_udn_control;
    // register for receive notification
    err = udn_chan_register_recv(&((b->udn_state).chan), _binding->waitset, (struct event_closure){  .handler = empty_udn_rx_handler,  .arg = _binding });
    if (err_is_fail(err)) {
        (_binding->error_handler)(_binding, err_push(err, LIB_ERR_CHAN_REGISTER_RECV));
    }
    
    return(err);
}

static  void empty_udn_new_monitor_binding_continuation(void *st, errval_t err, struct monitor_binding *monitor_binding)
{
    struct empty_binding *_binding = st;
    struct empty_udn_binding *b = st;
    
    if (err_is_fail(err)) {
        err = err_push(err, LIB_ERR_MONITOR_CLIENT_BIND);
        goto out;
    }
    
    ((b->udn_state).chan).monitor_binding = monitor_binding;
    // start the bind on the new monitor binding
    err = udn_chan_bind(&((b->udn_state).chan), (struct udn_bind_continuation){  .handler = empty_udn_bind_continuation,  .st = b }, &(_binding->event_qnode), b->iref, monitor_binding, NULL_CAP);
    
    out:
    if (err_is_fail(err)) {
        (_binding->bind_cont)(_binding->st, err, _binding);
        empty_udn_destroy(b);
    }
}

 errval_t empty_udn_bind(struct empty_udn_binding *b, iref_t iref, empty_bind_continuation_fn *_continuation, void *st, struct waitset *waitset, idc_bind_flags_t flags)
{
    errval_t err;
    (b->b).st = NULL;
    (b->b).waitset = waitset;
    event_mutex_init(&((b->b).mutex), waitset);
    (b->b).can_send = empty_udn_can_send;
    (b->b).register_send = empty_udn_register_send;
    (b->b).error_handler = empty_udn_default_error_handler;
    (b->b).tx_vtbl = empty_udn_tx_vtbl;
    memset(&((b->b).rx_vtbl), 0, sizeof((b->b).rx_vtbl));
    flounder_support_waitset_chanstate_init(&((b->b).register_chanstate));
    flounder_support_waitset_chanstate_init(&((b->b).tx_cont_chanstate));
    (b->b).tx_msgnum = 0;
    (b->b).rx_msgnum = 0;
    (b->b).tx_msg_fragment = 0;
    (b->b).rx_msg_fragment = 0;
    (b->b).tx_str_pos = 0;
    (b->b).rx_str_pos = 0;
    (b->b).tx_str_len = 0;
    (b->b).rx_str_len = 0;
    (b->b).bind_cont = NULL;
    flounder_stub_udn_state_init(&(b->udn_state), b);
    (b->b).change_waitset = empty_udn_change_waitset;
    (b->b).control = empty_udn_control;
    (b->b).st = st;
    (b->b).bind_cont = _continuation;
    b->iref = iref;
    
    // do we need a new monitor binding?
    if (flags & IDC_BIND_FLAG_RPC_CAP_TRANSFER) {
        err = monitor_client_new_binding(empty_udn_new_monitor_binding_continuation, b, waitset, DEFAULT_LMP_BUF_WORDS);
    } else {
        err = udn_chan_bind(&((b->udn_state).chan), (struct udn_bind_continuation){  .handler = empty_udn_bind_continuation,  .st = b }, &((b->b).event_qnode), iref, get_monitor_binding(), NULL_CAP);
    }
    
    if (err_is_fail(err)) {
        empty_udn_destroy(b);
    }
    return(err);
}


/*
 * Connect callback for export
 */
 errval_t empty_udn_connect_handler(void *st, struct monitor_binding *mb, uintptr_t mon_id, struct capref notify_cap, coreid_t dest_core_id, uint32_t out_chan_id, uint8_t dest_asid)
{
    struct empty_export *e = st;
    errval_t err;
    
    // allocate storage for binding
    struct empty_udn_binding *b = malloc(sizeof(struct empty_udn_binding ));
    if (b == NULL) {
        return(LIB_ERR_MALLOC_FAIL);
    }
    
    struct empty_binding *_binding = &(b->b);
    (b->b).st = NULL;
    (b->b).waitset = (e->waitset);
    event_mutex_init(&((b->b).mutex), e->waitset);
    (b->b).can_send = empty_udn_can_send;
    (b->b).register_send = empty_udn_register_send;
    (b->b).error_handler = empty_udn_default_error_handler;
    (b->b).tx_vtbl = empty_udn_tx_vtbl;
    memset(&((b->b).rx_vtbl), 0, sizeof((b->b).rx_vtbl));
    flounder_support_waitset_chanstate_init(&((b->b).register_chanstate));
    flounder_support_waitset_chanstate_init(&((b->b).tx_cont_chanstate));
    (b->b).tx_msgnum = 0;
    (b->b).rx_msgnum = 0;
    (b->b).tx_msg_fragment = 0;
    (b->b).rx_msg_fragment = 0;
    (b->b).tx_str_pos = 0;
    (b->b).rx_str_pos = 0;
    (b->b).tx_str_len = 0;
    (b->b).rx_str_len = 0;
    (b->b).bind_cont = NULL;
    flounder_stub_udn_state_init(&(b->udn_state), b);
    (b->b).change_waitset = empty_udn_change_waitset;
    (b->b).control = empty_udn_control;
    
    // run user's connect handler
    err = ((e->connect_cb)(e->st, _binding));
    if (err_is_fail(err)) {
        // connection refused
        empty_udn_destroy(b);
        return(err);
    }
    
    // accept the connection and setup the channel
    err = udn_chan_accept(&((b->udn_state).chan), mon_id, dest_core_id, out_chan_id, dest_asid);
    if (err_is_fail(err)) {
        err = err_push(err, LIB_ERR_UDN_CHAN_ACCEPT);
        (_binding->error_handler)(_binding, err);
        return(err);
    }
    
    // notify cap ignored
    // setup cap handlers
    (((b->udn_state).chan).cap_handlers).st = b;
    (((b->udn_state).chan).cap_handlers).cap_receive_handler = empty_udn_cap_rx_handler;
    
    // register for receive notification
    err = udn_chan_register_recv(&((b->udn_state).chan), _binding->waitset, (struct event_closure){  .handler = empty_udn_rx_handler,  .arg = _binding });
    if (err_is_fail(err)) {
        (_binding->error_handler)(_binding, err_push(err, LIB_ERR_CHAN_REGISTER_RECV));
    }
    
    // send back bind reply
    udn_chan_send_bind_reply(mb, &((b->udn_state).chan), SYS_ERR_OK, mon_id, NULL_CAP);
    
    return(SYS_ERR_OK);
}

#endif // CONFIG_FLOUNDER_BACKEND_UDN
